/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonSize,
} from './components/button/interface';

export namespace Components {
  interface ThermostatApp {
    'state': 'cool' | 'heat' | 'idle';
  }
  interface ThermostatButton {
    'checked': boolean;
    'disabled': boolean;
    'size': ButtonSize;
  }
  interface ThermostatButtonGroup {}
  interface ThermostatIcon {
    'glyph': string;
  }
}

declare global {


  interface HTMLThermostatAppElement extends Components.ThermostatApp, HTMLStencilElement {}
  var HTMLThermostatAppElement: {
    prototype: HTMLThermostatAppElement;
    new (): HTMLThermostatAppElement;
  };

  interface HTMLThermostatButtonElement extends Components.ThermostatButton, HTMLStencilElement {}
  var HTMLThermostatButtonElement: {
    prototype: HTMLThermostatButtonElement;
    new (): HTMLThermostatButtonElement;
  };

  interface HTMLThermostatButtonGroupElement extends Components.ThermostatButtonGroup, HTMLStencilElement {}
  var HTMLThermostatButtonGroupElement: {
    prototype: HTMLThermostatButtonGroupElement;
    new (): HTMLThermostatButtonGroupElement;
  };

  interface HTMLThermostatIconElement extends Components.ThermostatIcon, HTMLStencilElement {}
  var HTMLThermostatIconElement: {
    prototype: HTMLThermostatIconElement;
    new (): HTMLThermostatIconElement;
  };
  interface HTMLElementTagNameMap {
    'thermostat-app': HTMLThermostatAppElement;
    'thermostat-button': HTMLThermostatButtonElement;
    'thermostat-button-group': HTMLThermostatButtonGroupElement;
    'thermostat-icon': HTMLThermostatIconElement;
  }
}

declare namespace LocalJSX {
  interface ThermostatApp extends JSXBase.HTMLAttributes<HTMLThermostatAppElement> {
    'state'?: 'cool' | 'heat' | 'idle';
  }
  interface ThermostatButton extends JSXBase.HTMLAttributes<HTMLThermostatButtonElement> {
    'checked'?: boolean;
    'disabled'?: boolean;
    'size'?: ButtonSize;
  }
  interface ThermostatButtonGroup extends JSXBase.HTMLAttributes<HTMLThermostatButtonGroupElement> {}
  interface ThermostatIcon extends JSXBase.HTMLAttributes<HTMLThermostatIconElement> {
    'glyph'?: string;
  }

  interface IntrinsicElements {
    'thermostat-app': ThermostatApp;
    'thermostat-button': ThermostatButton;
    'thermostat-button-group': ThermostatButtonGroup;
    'thermostat-icon': ThermostatIcon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


